### ISSUE TITLE
ESP32 machines not available (QEMU-187)

### ISSUE THREAD

**Issue by big-vl** [espressif/qemu#96]
```
[big-vl@ho qemu]$ sudo build/qemu-system-xtensa -machine help
[sudo] password for big-vl: 
==207161==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
Supported machines are:
kc705                kc705 EVB (dc232b)
kc705-nommu          kc705 noMMU EVB (de212)
lx200                lx200 EVB (dc232b)
lx200-nommu          lx200 noMMU EVB (de212)
lx60                 lx60 EVB (dc232b)
lx60-nommu           lx60 noMMU EVB (de212)
ml605                ml605 EVB (dc232b)
ml605-nommu          ml605 noMMU EVB (de212)
none                 empty machine
sim                  sim machine (dc232b) (default)
virt                 virt machine (dc232b)

=================================================================
==207161==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x75d9ba8e1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x75d9ba075762 in g_malloc (/usr/lib/libglib-2.0.so.0+0x62762) (BuildId: adcf94ff81298387baa7b55fa88c9ba80b3283a6)

Indirect leak of 112 byte(s) in 7 object(s) allocated from:
    #0 0x75d9ba8e1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x75d9ba075762 in g_malloc (/usr/lib/libglib-2.0.so.0+0x62762) (BuildId: adcf94ff81298387baa7b55fa88c9ba80b3283a6)

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 8 allocation(s).
```

There are no esp32 machines available, I rebuilt it several times, how do I add a machine there?

I have archlinux.

**Comment by big-vl** [comment]
I had to completely clear the files from the git folder after unsuccessful builds, esp32 appeared.
